# Numpy => numeric python

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\suraj\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [3]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
type(arr)

numpy.ndarray

In [5]:
print(arr[1])

2


In [6]:
print(arr[-1])

5


## slicing

In [7]:
arr[2:5:1]

array([3, 4, 5])

In [8]:
arr[2:5]

array([3, 4, 5])

In [9]:
arr[2:]

array([3, 4, 5])

In [10]:
arr[:3]

array([1, 2, 3])

## 2-D

In [11]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr.ndim

1

In [13]:
arr2.ndim

2

In [14]:
arr2.shape

(3, 3)

In [15]:
arr2.size

9

In [16]:
arr.size

5

In [17]:
zero_arr=np.zeros((7,5))
zero_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zero_arr1=np.zeros((3,4),dtype=int)
zero_arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
ones_arr=np.ones((3,4))
ones_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
ones_arr=np.ones((3,4),dtype=int)
ones_arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
full=np.full((3,4),fill_value=2)
full

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [22]:
eye_arr= np.eye(5, dtype=int)
eye_arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [23]:
eye_arr1= np.eye(5, dtype=int, k=1)
eye_arr1

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [24]:
# left to right 
np.fliplr(eye_arr)

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0]])

## range

In [25]:
rng=np.array(range(3))
rng

array([0, 1, 2])

In [26]:
arange_arr=np.arange(0,10)
arange_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [28]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## transpose

In [29]:
t_ar = np.transpose(arr2)
t_ar

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [30]:
arr2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## reshape

In [31]:
arange_arr.size

10

In [32]:
arange_arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## math op

In [33]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [34]:
x+y

array([[ 6,  8],
       [10, 12]])

In [35]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [36]:
y-x

array([[4, 4],
       [4, 4]])

In [37]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [38]:
y/x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [39]:
np.divide(y,x)

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [40]:
x*y

array([[ 5, 12],
       [21, 32]])

In [41]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [42]:
np.matmul(x,y)

array([[19, 22],
       [43, 50]])

In [43]:
x@y

array([[19, 22],
       [43, 50]])

In [44]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [45]:
x.flatten()

array([1, 2, 3, 4])

In [46]:
row=int(input())
col=int(input())
a= np.ones((3,4), dtype =int)
a[1:-1,1:-1]=0
# for i in range(3):
#     for j in range(col):
#         if(i==0 or i==row-1 or j == 0 or j == col-1):
#             a[i][j]=1
a

5
4


array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

## stacking

In [47]:
print(x)
print(y)
np.hstack((x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [48]:
np.vstack((x,y))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [49]:
x=np.eye(3, dtype=int)

In [50]:
x

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [51]:
np.hstack((x,x,x))

array([[1, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 1]])

In [52]:
np.vstack((x,x,x))

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [53]:
# Given array 
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
B=A.T
B

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [55]:
A.T.reshape(2,6)

array([[ 1,  5,  9,  2,  6, 10],
       [ 3,  7, 11,  4,  8, 12]])